### ISSUE TITLE
Decide keyboard layout

### ISSUE THREAD

**Issue by wstrm** [Sweboard/Swolemak#1]

**Comment by wstrm** [comment]
@Hjortsberg Please upload preliminary keyboard layout represented as a portable network graphics, please.

**Comment by Hjortsberg** [comment]
Here is the preliminary layout, please share your thoughts and comments if any.

![swolemak- mitosis-colemak-sv-se](https://user-images.githubusercontent.com/17297258/46953382-0275ad00-d08e-11e8-910c-b9cec565c8d3.png)

**Comment by wstrm** [comment]
VERY GOOD. Let's start voting.

**Comment by wstrm** [comment]
AYE!

**Comment by Hjortsberg** [comment]
Yes!

**Comment by wstrm** [comment]
Unknown command, please select between AYE!/NAY!

**Comment by Hjortsberg** [comment]
AYE

**Comment by wstrm** [comment]
Unknown command, please select between AYE!/NAY!

**Comment by Hjortsberg** [comment]
AYE!

**Comment by wstrm** [comment]
# VOTE RESULT
FOR: 2 (100%)
AGAINST: 0 (0%)
