### ISSUE TITLE
Illustration of new layout in keyboards/mitosis

### ISSUE THREAD

**Issue by Hjortsberg** [Sweboard/Swolemak#26]
Hi, I have this keyboard with a swolemak firmware flashed already. But i don't know if I want to flash the new master firmware without knowing what I'm flashing. Is it possible to get a illustration?

**Comment by Hjortsberg** [comment]
Ignore this.

**Comment by wstrm** [comment]
Lål

// Written on my Mitosis

**Comment by wstrm** [comment]
Do you want the hex?
