### ISSUE TITLE
Right bracket is instead mapped to plus sign.

### ISSUE THREAD

**Issue by Hjortsberg** [Sweboard/Swolemak#29]
Pressing the fn key and k should make a right bracket but instead generates a plus sign, according to the picture of the layout.

**Comment by wstrm** [comment]
Woooops https://github.com/Sweboard/qmk_firmware/blob/mitosis-swolemak/keyboards/mitosis/keymaps/swolemak/keymap.c#L94

**Comment by wstrm** [comment]
Fixed: https://github.com/Sweboard/Swolemak/releases/tag/v0.0.1-rc2
