### ISSUE TITLE
Add portable network graphics representation generated using computer-aided design of decided keyboard layout

### ISSUE THREAD

**Issue by Hjortsberg** [Sweboard/Swolemak#3]
Using keyboard-layout-editor.com, create and add the decided keyboard layout.

**Comment by wstrm** [comment]
`Okay`

**Comment by Hjortsberg** [comment]
Here is the preliminary layout, please share your thoughts and comments if any.

![swolemak- mitosis-colemak-sv-se](https://user-images.githubusercontent.com/17297258/46953217-8bd8af80-d08d-11e8-980b-f824c2003530.png)

**Comment by wstrm** [comment]
Blocked by #4
